baseurl: "https://agapovone.github.io"
languageCode: en-us
title: Agapov Alexey
theme: tania
paginate: 6

params:
  titleEmoji: "\U0001F92F"
  titleLogo: ""
  enableFootnotes: true
  siteName: Alexey Agapov blog
  siteDesc: iOS and nothing else.
  author: Alexey Agapov
  maxCategoryToShow: 10
  socialOptions:
    dev-to: ""
    email: ""
    facebook: ""
    github: ""
    instagram: ""
    linkedin: ""
    medium: ""
    stack-overflow: ""
    steam: ""
    telegram: ""
    twitter: "https://twitter.com/agapov_one"
    twitch: ""
    whatsapp: ""
menu:
  header:
    - name: Articles
      url: /articles/
    - name: About me
      url: /about/
  footer:
    - name: RSS
      url: /index.xml
markup:
  highlight:
    lineNos: true
    style: dracula
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - JSON
