baseurl: "https://agapovone.github.io"
languageCode: ru-ru
title: Agapov Alexey
theme: tania
paginate: 6

defaultContentLanguage: ru
params:
  titleEmoji: "\U0001F92F"
  titleLogo: ""
  enableFootnotes: true
  siteName: Agapov Alexey blog.
  siteDesc: iOS and nothing else
  author: Agapov Alexey
  maxCategoryToShow: 10
  socialOptions:
    dev-to: ""
    email: ""
    facebook: ""
    github: "https://github.com/AgapovOne"
    instagram: ""
    linkedin: ""
    medium: ""
    stack-overflow: ""
    steam: ""
    telegram: "http://t.me/agapov_one"
    twitter: "https://twitter.com/agapov_one"
    twitch: ""
    whatsapp: ""
menu:
  header:
    - name: Articles
      url: /articles/
    # - name: Tags
    #   url: /tags/
    # - name: About me
    #   url: /about/
  footer:
    - name: RSS
      url: /index.xml
markup:
  highlight:
    lineNos: true
    style: dracula
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - JSON
