baseURL = "https://agapovone.github.io/"
languageCode = "en-US"
title = "Alexey Agapov Blog"
theme = "agapovblist"

[params]
  description = "Modern blog theme for your Hugo site."
  name = "Blist Theme"

  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Agapov Alexey · All rights reserved"
  favicon = "favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-yellow-100"

[params.homepage]
  title = "Hey! I'm Agapov Alexey"
  description = "27 y/o developer from Yekaterinburg, working @ Kontur"

[params.homepage.social]
  description = "I work on everything coding and tweet never"
  twitter = "https://twitter.com/agapov_one"
  github = "https://github.com/AgapovOne"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
